---
- name: Замена дефолтной страницы Apache
  hosts: manage_nodes
  become: yes
  tasks:
    - name: Создать кастомную страницу
      ansible.builtin.copy:
        content: |
          <html>
            <body>
              <h1>Цывин Илья, группа С1-21</h1>
            </body>
          </html>
        dest: /var/www/html/index.html
        mode: 0644

    - name: Перезапустить Apache
      ansible.builtin.service:
        name: httpd
        state: restarted
